spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          #什么时候去百度，就要符合某种断言规则
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          #什么时候去qq，就要符合某种断言规则
          predicates:
            - Query=url,qq

#注意：要把顺序给调换一下，要不然转不到product里面的，把精确的路由放在高优先级
        - id: product_route
          uri: lb://gulimall-product
          predicates:
             - Path=/api/product/**   #优先适配这里的断言，不是下面的
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#http://localhost:88/api/product/category/list/tree
#转成http://localhost:10000/product/category/list/tree

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**   #优先适配这里的断言，不是下面的
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
        uri: lb://gulimall-member
        predicates:
          - Path=/api/member/**   #优先适配这里的断言，不是下面的
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
        uri: lb://gulimall-ware
        predicates:
        - Path=/api/ware/**   #优先适配这里的断言，不是下面的
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast  #lb负载均衡，负载均衡到指定的服务，将请求的地址路由给他
          predicates:
            - Path=/api/**  #后台管理系统发的api请求都先直接路由到
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#前端项目，发送请求都带上前缀 /api
#http://localhost:88/api/captcha.jpg
#上面的路径要转成真正能访问的这个路径http://localhost:8080/renren-fast/captcha.jpg
#要把api改成renren-fast
#可以使用网关带的路径重写filters: - RewritePath


#这段配置要放在最后面，防止出现匹配出现异常
        - id: gulimall_host_route
          uri: lb://gulimall-product  #lb负载均衡，负载均衡到指定的服务,将请求的地址路由给他
          predicates: #域名的规则
            - Host=gulimall.com,item.gulimall.com   # **:就是任意的子域名
#就是gulimall.com下的所有请求，都转给gulimall-product


        - id: gulimall_search_route
          uri: lb://gulimall-search  #lb负载均衡，负载均衡到指定的服务,将请求的地址路由给他
          predicates: #域名的规则
            - Host=search.gulimall.com


        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server  #lb负载均衡，负载均衡到指定的服务,将请求的地址路由给他
          predicates: #域名的规则
            - Host=auth.gulimall.com

        - id: gulimall_cart_route
          uri: lb://gulimall-cart  #lb负载均衡，负载均衡到指定的服务,将请求的地址路由给他
          predicates: #域名的规则
            - Host=cart.gulimall.com


